// Globale Funktionen der FiveM-Server-Laufzeit (nur die hier verwendeten)
declare function onNet(name: string, cb: (...args: any[]) => void): void;
declare function emitNet(name: string, target: number | string, ...args: any[]): void;
declare function on(name: string, cb: (...args: any[]) => void): void;
declare function emit(name: string, ...args: any[]): void;
declare const exports: any;
declare function GetPlayerName(src: number | string): string | null;
declare function GetCurrentResourceName(): string;
declare function GetResourcePath(name: string): string;
declare const source: number;
declare function GetPlayerPed(src: number | string): number;
declare function GetEntityCoords(ent: number): [number, number, number];
declare function GetEntityHeading(ent: number): number;
declare function GetEntityModel(ent: number): number;
declare function DoesEntityExist(ent: number): boolean;
declare function NetworkGetEntityFromNetworkId(netId: number): number;
declare function GetVehiclePedIsIn(ped: number, lastVehicle: boolean): number;
declare function IsPlayerAceAllowed(src: number | string, ace: string): boolean;
declare function GetNumPlayerIdentifiers(src: number | string): number;
declare function GetPlayerIdentifier(src: number | string, idx: number): string;
declare function GetResourceState(name: string): string;
declare function GetEntityHealth(ent: number): number;
